# Generated by Django 3.2.9 on 2021-12-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('state', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('done', 'done'), ('archived', 'archived')], default='draft', max_length=50)),
            ],
        ),
    ]
